name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Code auschecken
        uses: actions/checkout@v4

      - name: App stoppen
        run: sudo systemctl stop myapp

      - name: Restore & Publish
        run: |
          dotnet restore
          dotnet publish -c Release -o /var/www/myapp

      - name: App starten
        run: sudo systemctl start myapp
